version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: incident-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: ./app
    container_name: incident-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always
    # BUG: We are NOT setting REDIS_HOST here â†’ app fails
    environment:
      - REDIS_HOST=redis
